### ISSUE TITLE
It would be nice to have CSProject poses for zelda/sheik individually

### ISSUE THREAD

**Issue by NickCondron** [AeonSSB/Melee-CSProject#1]
Is this possible? This repo is awesome.

**Comment by AeonSSB** [comment]
You can hide the objects related to either character and adjust the camera positions to better compliment the UI output with the other one alone.

To hide an object, click on the eye and the monitor icons on the right of its name in the top right panel. You'll have to do that for every object of one of the two characters, including some that are part of the "Stock" collection at the bottom of the list. The Stock collection is usually turned off, after you hide the objects make sure to turn it off again so that the output renders don't show objects that are meant to appear only in stocks in the other assets too.

Once that's done, in the center panel you can select each camera from the Camera Manager and adjust its position. Each camera renders a distinct assets, for example one controls the full body render while another one the CSP. Assuming you hide either Zelda or Sheik from their shared scene, repositioning each camera is strongly recommended for better render outputs. You can see how the Melee poses are cropped with the cameras to have a reference on the space the character should occupy.

Sorry for the late response.

**Comment by NickCondron** [comment]
I downloaded latest blender and I was able to hide sheik/zelda based on your instructions. I was able to adjust the cameras' focal lengths and shifts x/y to better align to the solo subject (I don't have much of an artists eye, though so idk if the results would be good). however, I can't figure out how to render the cameras to image.

I found this video https://www.youtube.com/watch?v=wjYgeOlG_4g but some of the menus/toolbars are not where they are for me. I messed around for 20 minutes and couldn't figure it out 😞.

I appreciate your help! Fwiw I'm developing an analysis app for slippi replays and I intend to use the additional csproject poses for additional visual variety alongside the melee poses.

**Comment by AeonSSB** [comment]
In order to make the menus work you need to download Blender 3.5.1 and install the 2 add-ons in the Resources folder. This document covers everything: https://docs.google.com/document/d/1BowqszIEaXATT7Ey793StTHZT2AJBy20oLLB5Q6zwL4/edit?usp=sharing

I'll make sure to include this in the description of the repo

**Comment by NickCondron** [comment]
I got it to work! Thank you. I will include this project in the credits.
